{% set version = "2.32.0.20241016" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-requests/types-requests-{{ version }}.tar.gz
  sha256: 0d9cad2f27515d0e3e3da7134a1b6f28fb97129d86b867f24d9c726452634d95

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - urllib3 >=2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
