{% set version = "2.32.0.20240521" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/types-requests/types-requests-{{ version }}.tar.gz
  sha256: c5c4a0ae95aad51f1bf6dae9eed04a78f7f2575d4b171da37b622e08b93eb5d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - urllib3 >=2

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
