schema_version: 1

context:
  version: "2.33.0.20260402"

package:
  name: types-requests
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-requests/types_requests-${{ version }}.tar.gz
  sha256: 1bdd3ada9b869741c5c4b887d2c8b4e38284a1449751823b5ebbccba3eefd9da

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - urllib3 >=2

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
  - package_contents:
      site_packages:
        - requests-stubs/__init__.pyi

about:
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed
  repository: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
